# Generated by Django 5.1.4 on 2024-12-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='seuil_critique',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
