# Generated by Django 5.1.4 on 2024-12-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_produit_seuil_critique_alter_produit_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='quantite_en_stock',
            field=models.IntegerField(default=1),
        ),
    ]
