# Generated by Django 5.1.4 on 2024-12-31 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_produit_quantite_en_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='quantite_en_stock',
            new_name='quantiteEnStock',
        ),
    ]
