# Generated by Django 5.1.4 on 2024-12-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_rename_quantiteenstock_produit_quantite_en_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='client_nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commandefournisseur',
            name='fournisseur_nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='date_commande',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='date_commande',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commandefournisseur',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
    ]
