# Generated by Django 5.1.4 on 2024-12-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_commandefournisseur_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validée', 'Validée'), ('envoyée', 'Envoyée')], default='en_attente', max_length=10),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commandeclient',
            name='quantite',
            field=models.IntegerField(),
        ),
    ]
