# Generated by Django 5.1.4 on 2025-01-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
